### ISSUE TITLE
卸载插件时报错，然后无法再次安装

### ISSUE THREAD

**Issue by spicylobster** [xu-li/cordova-plugin-wechat#124]
卸载时报错
Uninstalling xu.li.cordova.wechat from android
Uninstalling xu.li.cordova.wechat from ios
TypeError: Cannot read property 'buffer' of undefined
    at walk_obj (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/plist/lib/build.js:131:18)
    at walk_obj (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/plist/lib/build.js:98:7)
    at walk_obj (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/plist/lib/build.js:109:9)
    at Object.build (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/plist/lib/build.js:76:3)
    at ConfigFile_save [as save] (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/ConfigFile.js:97:47)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/ConfigKeeper.js:61:49
    at Array.forEach (native)
    at ConfigKeeper_save_all [as save_all] (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/ConfigKeeper.js:59:31)
    at PlatformMunger_save_all [as save_all] (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/config-changes.js:82:24)
    at Object.exports.process (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/config-changes.js:59:12)

之后prepare也会报同样错误
platform remove后重新platform add仍然无法使用

报错： CDVPlugin class CDVWechat (pluginName: Wechat) does not exist.
尝试添加源代码后，报14个编译错误
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_WXVideoObject", referenced from:
      objc-class-ref in CDVWechat-F6E00D80E619357D.o
  "_OBJC_CLASS_$_WXEmoticonObject", referenced from:
      objc-class-ref in CDVWechat-F6E00D80E619357D.o
  "_OBJC_CLASS_$_WXImageObject", referenced from:
      objc-class-ref in CDVWechat-F6E00D80E619357D.o
...

**Comment by spicylobster** [comment]
重新尝试 platform remove ios 并 platform add ios后成功，但之前自己ios的一些配置只能重新尝试恢复，plugin remove前请小心，切记备份

**Comment by xu-li** [comment]
多谢提醒。
