### ISSUE TITLE
ios端，1.1.1版本，卸载不了

### ISSUE THREAD

**Issue by hyitclj** [xu-li/cordova-plugin-wechat#152]
卸载总是错误，然后项目build就不通过了，项目就死了（我先备份的），卸载其他插件很ok，为什么啊，怎么办啊。想装1.1.2的呢。。。怎么办

**Comment by xu-li** [comment]
所以，错误是？

**Comment by hyitclj** [comment]
wujiedeMacBook-Pro:ShortSightedness wujie$ cordova plugin rm cordova-plugin-wechat
Uninstalling cordova-plugin-wechat
TypeError: Cannot read property 'buffer' of undefined
    at walk_obj (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/plist/lib/build.js:131:18)
    at walk_obj (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/plist/lib/build.js:98:7)
    at walk_obj (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/plist/lib/build.js:109:9)
    at Object.build (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/plist/lib/build.js:76:3)
    at ConfigFile_save [as save] (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/ConfigFile.js:97:47)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/ConfigKeeper.js:61:49
    at Array.forEach (native)
    at ConfigKeeper_save_all [as save_all] (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/ConfigKeeper.js:59:31)
    at PlatformMunger_save_all [as save_all] (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/config-changes.js:82:24)
    at Object.exports.process (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/config-changes.js:59:12)

**Comment by xu-li** [comment]
See [FAQ](https://github.com/xu-li/cordova-plugin-wechat/wiki/FAQ#typeerror-cannot-read-property-buffer-of-undefined).

**Comment by hyitclj** [comment]
悄悄地说一句。。。还缺一点点。。怎么解决的呢？

**Comment by xu-li** [comment]
看[这里](https://issues.apache.org/jira/browse/CB-7781?focusedCommentId=14902438&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14902438)。

1.  备份一下。
```
sudo cp /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/plist/lib/build.js /tmp/build.js.bak
```

2. 参照[这里](https://github.com/aetchegoyen/plist.js/commit/6eed7aedbee90db2315b985cb952778696190ba0)，修改/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/plist/lib/build.js
