### ISSUE TITLE
添加cordova报错

### ISSUE THREAD

**Issue by mick-cs** [xu-li/cordova-plugin-wechat#47]
你好，我安装你提供的方法添加插件，结果报错，错误信息如下

    Fetching plugin "https://github.com/xu-li/cordova-plugin-wechat.git" via git clone
    Repository "https://github.com/xu-li/cordova-plugin-wechat.git" checked out to git ref "master".
    shell.js: internal error
    Error: EXDEV, cross-device link not permitted 'C:\Users\ADMINI~1\AppData\Local\Temp\git\1438249154411\plugin.xml'
    at Error (native)
    at Object.fs.renameSync (fs.js:638:18)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\shelljs\src\mv.js:77:8
    at Array.forEach (native)
    at Object._mv (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\shelljs\src\mv.js:53:11)
    at Object.mv (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\shelljs\src\common.js:186:23)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\util\plugins.js:53:19
    at _fulfilled (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:749:13)``

请问是怎么回事？

**Comment by xu-li** [comment]
@mick-cs 这个是cordova的bug。请查看[Plugin install via git url error "cross-device link not permitted"
](https://issues.apache.org/jira/browse/CB-9212).
