### ISSUE TITLE
安卓 微信分享 取消时闪退

### ISSUE THREAD

**Issue by mbossX** [xu-li/cordova-plugin-wechat#533]
安卓 分享时点取消会闪退，不取消的话正常，支付啥的都正常，ios 一切正常

```
2019-05-02 13:40:34.281 26631-26631/cn.itvmedia.app W/ViewRootImpl[MainActivity]: Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=158, metaState=0, flags=0x68, repeatCount=0, eventTime=94139935, downTime=94139836, deviceId=8, source=0x101 }
2019-05-02 13:40:34.316 26631-26631/cn.itvmedia.app V/MicroMsg.SDK.WXApiImplV10.ActivityLifecycleCb: cn.itvmedia.app.MainActivity  onActivityPaused
2019-05-02 13:40:34.317 26631-26631/cn.itvmedia.app D/CordovaActivity: Paused the activity.
2019-05-02 13:40:34.710 26631-26631/cn.itvmedia.app D/CordovaActivity: Stopped the activity.
2019-05-02 13:40:34.710 26631-26631/cn.itvmedia.app D/CordovaActivity: CordovaActivity.onDestroy()
2019-05-02 13:40:34.717 26631-26631/cn.itvmedia.app D/CordovaWebViewImpl: >>> loadUrl(about:blank)
2019-05-02 13:40:34.725 26631-26631/cn.itvmedia.app W/cr_AwContents: WebView.destroy() called while WebView is still attached to window.
2019-05-02 13:40:34.753 26631-26631/cn.itvmedia.app W/cr_AwContents: Application attempted to call on a destroyed WebView
    java.lang.Throwable
        at org.chromium.android_webview.AwContents.f(PG:337)
        at org.chromium.android_webview.AwContents.a(PG:311)
        at org.chromium.android_webview.AwContents.q(PG:572)
        at zT.loadingStateChanged(PG:159)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:331)
        at android.os.Looper.loop(Looper.java:149)
        at android.app.ActivityThread.main(ActivityThread.java:6701)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:249)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
2019-05-02 13:40:35.042 26631-26656/cn.itvmedia.app W/cr_ChildProcessConn: onServiceDisconnected (crash or killed by oom): pid=18168
```
这是闪退时的日志

插件版本 2.6.0
`<engine name="android" spec="7.1.4" />`

之前没问题，后面开发其他功能，不知道哪里不对了，找了很久也没找到原因。

**Comment by mbossX** [comment]
```
private share(type) {
    if (!type) {
      return;
    }
    if (type === 'wechat' || type === 'time-line') {
      this.wechat.share({
        message: {
          title: "精准传媒",
          description: "精准传媒 精彩世界",
          thumb: "assets/img/icon.png",
          // mediaTagName: "TEST-TAG-001",
          messageExt: "精准传媒专注社区广告, 随时随地做宣传",
          // messageAction: "<action></action>",
          media: {
            type: WechatOption.Type.WEBPAGE,
            webpageUrl: ConfigService.URL_QRCODE + `${this.user.username}`
          }
        },
        scene: type === 'wechat' ? WechatOption.Scene.SESSION : WechatOption.Scene.TIMELINE
      }).catch(err => {
        console.error(err);
      });
    }
  }
```
这是调用代码

我试了最新的2.8.0版本，还是同样的问题

而且我发现，如果是点击微信分享页面左上角的回退按钮可以回到app，但是直接按安卓的硬会退按钮就会闪退

**Comment by xlfdyzcs** [comment]
https://jasonz1987.github.io/cordova-wechat-docs/docs/faq
