### ISSUE TITLE
2.8版本 cordova build 报错

### ISSUE THREAD

**Issue by jiwufeiyang** [xu-li/cordova-plugin-wechat#538]
android 安装最新插件时报错
Installing "cordova-plugin-wechat" for android
Android Studio project detected
Subproject Path: CordovaLib
Subproject Path: app
Failed to install 'cordova-plugin-wechat': Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at module.exports (/home/wen/work/cordova/dep/chezixiang/plugins/cordova-plugin-wechat/scripts/android-install.js:7:23)
    at runScriptViaModuleLoader (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:188:18)
    at runScript (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:164:16)
    at /usr/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:132:20
    at _fulfilled (/usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30)
(node:9948) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot find module 'semver'

**Comment by jiwufeiyang** [comment]
大神们帮我找着原因谢谢！ 另外我安装 cordova plugin add cordova-plugin-wechat@2.7.2 是可以得点击支付app会闪退，
cordova plugin add cordova-plugin-wechat@2.7.0 提示 参数错误

**Comment by jiwufeiyang** [comment]
升级cordova 9.0后插件可以运行了，但是报普通错误

**Comment by jiwufeiyang** [comment]
感谢， cordova build --release 后安装ok了
