### ISSUE TITLE
添加plugin时出错

### ISSUE THREAD

**Issue by zhangv** [xu-li/cordova-plugin-wechat#98]
运行：
ionic plugin add https://github.com/xu-li/cordova-plugin-wechat --variable wechatappid=[appid]
出错：
Running android-install.Hook: after_plugin_add, Package: com.xxx.app, Path: /Users/xxx/Develop/app/xxxapp.
Saving plugin to package.json file
Error happened [TypeError: Cannot convert undefined or null to object]
TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at Object.getPluginFromFetchJsonByLocator (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/state.js:734:26)
    at Object.savePlugin (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/state.js:670:36)
    at /usr/local/lib/node_modules/ionic/lib/ionic/cordova.js:90:22
    at _fulfilled (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)

**Comment by xu-li** [comment]
什么版本的ionic？

出错了以后，插件安装成功了么？

**Comment by zhangv** [comment]
1.7.7
安装后暂时还没发现异常，可以用。

**Comment by zwacky** [comment]
looks like there is something wrong with your `fetch.json` file. mind posting it, @zhangv?

**Comment by zhangv** [comment]
archive时报错：
ld: bitcode bundle could not be generated because '/Users/PATH/app/platforms/ios/myapp/Plugins/xu.li.cordova.wechat/libWeChatSDK.a(WapAuthHandler.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7

**Comment by zhangv** [comment]
@zwacky , here it is:
{
    "com.ionic.keyboard": {
        "source": {
            "type": "registry",
            "id": "com.ionic.keyboard"
        }
    },
    "ionic-plugin-keyboard": {
        "source": {
            "type": "git",
            "url": "https://github.com/driftyco/ionic-plugins-keyboard.git",
            "subdir": "."
        }
    },
    "xu.li.cordova.wechat": {
        "source": {
            "type": "git",
            "url": "https://github.com/xu-li/cordova-plugin-wechat",
            "subdir": "."
        }
    }
}

**Comment by zhangv** [comment]
在xcode里Build Setting => Build Options => Enable Bitcode 修改为no，就可以了。
然而我并不知道原因。。。
